version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: esports-db
    restart: always
    environment:
      POSTGRES_USER: esports
      POSTGRES_PASSWORD: esportspassword
      POSTGRES_DB: esports
    ports:
      - "5432:5432"
    volumes:
      - esports-db-data:/var/lib/postgresql/data

volumes:
  esports-db-data:
